### PR TITLE
Adds new NOT ILIKE/LIKE operations to pREST

### PR DESCRIPTION
**Pull request by vmesel**
This pull request adds the NOT operator to ILIKE and LIKE operations in PostgreSQL.

### CODE REVIEW

**Review by arxdsilva — COMMENTED** [review]
Could you add some unit test to this func, just so we ensure that it works later too? Thanks for the contribution!

**Comment by vmesel** [comment]
@arxdsilva where are the tests for this functionality located?

**Comment by arxdsilva** [comment]
> @arxdsilva where are the tests for this functionality located?

Usually on the same folder with <file>_test.go name, if there isnt you can create and just add your cases and it’ll be enough, later we can add more for the other cases

**Review by arxdsilva — APPROVED** [review]

**Comment by arxdsilva** [comment]
Thank you for your contribution!

**Pull request merged**
