### PR TITLE
Fixes docker build tagging for releases

### PR DESCRIPTION
**Pull request by vmesel**
We have a problem nowadays with our docker registry and tagging. With this in mind, I've created `release.yml` so we can deploy all of our releases.

In order to this PR to function, we need to set these env vars:

 - DOCKER_USERNAME
 - DOCKER_PASSWORD
 - GH_TOKEN

### CODE REVIEW

**Comment by avelino** [comment]
@vmesel this files workflow register image in hub.docker.com
https://github.com/prest/prest/blob/71c7eda28995f428db58ab9b488ad8a73657f917/.github/workflows/build.yml#L112-L143

if it is not registering, you need to fix it, not create another one
ref https://github.com/prest/prest/actions/runs/3849239259/jobs/6558001305#step:12:22

**Comment by vmesel** [comment]
@avelino it register to both registries

**Comment by vmesel** [comment]
@avelino can you help us here?

**Comment by arxdsilva** [comment]
@vmesel I've updated the env variables and will try to add a new tag now to double check if the builder now works, otherwise we'll work on this. Anyway we should split when possible the PR test action from release, so it is easier to understand and debug.

**Comment by vmesel** [comment]
@arxdsilva, @avelino just solved the issue. I'm closing this PR, and if we detect more bugs from our release process, we can rollback this PR in.

**Pull request closed without merging**
