### PR TITLE
issue_775_root_fatal

### LINKED ISSUE #775: Documentation quick start scaffold not working for me
when trying to use the application via docker-compose I can't create the minimum structure for jwt

Command:
```
 docker-compose exec prest prestd migrate up auth --url "postgres://prest:prest@postgres:5432/prest?sslmode=disable&sslcert=&sslkey=&sslrootcert="
```
Console messages:
```
2023/01/31 21:16:37 [warning] file './prest.toml' not found, falling back to default settings
2023/01/31 21:16:37 [warning] read env config error: Config File "prest" Not Found in "[/app]"
2023/01/31 21:16:37 [warning]
You are using v1 of prestd configs, please migrate to v2.

v1 will be deprecated soon.

View more at https://docs.prestd.com/prestd/deployment/server-configuration
pq: syntax error at or near "%"Error: pq: syntax error at or near "%"
Usage:
  prestd migrate up auth [flags]

Flags:
  -h, --help   help for auth

Global Flags:
      --path string   Migrations directory
      --url string    Database driver url (default "postgres://prest:prest@postgres:5432/prest?sslmode=disable&sslcert=&sslkey=&sslrootcert=")

pq: syntax error at or near "%"
```

I'm going to do a simple test, I don't want to make several configurations in files and etc.

Docker compose file:
```
version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=prest
      - POSTGRES_DB=prest
      - POSTGRES_PASSWORD=prest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "prest"]
      interval: 30s
      retries: 3
  prest:
    # use latest build - analyze the risk of using this version in production
    image: prest/prest:v1
    links:
      - "postgres:postgres"
    environment:
      - PREST_DEBUG=true
      - PREST_AUTH_ENABLED=false
      - PREST_PG_HOST=postgres
      - PREST_PG_USER=prest
      - PREST_PG_PASS=prest
      - PREST_PG_DATABASE=prest
      - PREST_PG_PORT=5432
      - PREST_SSL_MODE=disable
      - PREST_CACHE_ENABLED=false
      - PREST_CACHE=false
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
```

### PR DESCRIPTION
**Pull request by Listener430**
Fix #775 + removing `FATAL: role "root" does not exist error`

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
Issue #775 fixed in #786

User sprintf is not safe to use in queries, exec receives parameters

**Comment by avelino** [comment]
> pq: syntax error at or near "$1"

Check my comment [here](https://github.com/prest/prest/pull/788#discussion_r1148132588), I talk about using `fmt.Sprintf`

**Comment by Listener430** [comment]
Right, I see.
But replacing table name with placeholders $1 does not work, because you can only use them for values or where conditions. It genrates the same error near $1 as before next to %.
func QuoteIdentifier instead is made specifically to mitigate risk of SQL injection for fmt.Sprintf as in example below from the doc https://pkg.go.dev/github.com/lib/pq#QuoteIdentifier
QuoteIdentifier quotes an "identifier" (e.g. a table or a column name) to be used as part of an SQL statement. For example:

tblname := "my_table"
data := "my_data"
quoted := pq.QuoteIdentifier(tblname)
err := db.Exec(fmt.Sprintf("INSERT INTO %s VALUES ($1)", quoted), data)
Any double quotes in name will be escaped. The quoted identifier will be case sensitive when used in a query. If the input string contains a zero byte, the result will be truncated immediately before it.

**Review by arxdsilva — APPROVED** [review]
now LGTM

**Review by avelino — APPROVED** [review]

**Pull request merged**
