### PR TITLE
Fix insertTableNameRegex to support hyphen in dbname

### LINKED ISSUE #369: POST request failure when connected with a database having hyphen in the db name
{
	"error": "unable to find table name"
}
I'm getting this response when making POST request to a db having hyphen in the db name. eg db name: "my-db".
GET, PUT, PATCH and DELETE are working fine.

### PR DESCRIPTION
**Pull request by sarath16933**
Signed-off-by: Sarath <sveedu@akamai.com>

### CODE REVIEW

**Comment by sarath16933** [comment]
This commit fixes #369

**Comment by avelino** [comment]
@sarath16933 can you write a unit test to validate your change?

**Comment by sarath16933** [comment]
> @sarath16933 can you write a unit test to validate your change?

Sure.

**Comment by saqwel** [comment]
Hi, could you say, when this fix will be available in new version?

**Comment by avelino** [comment]
> Hi, could you say, when this fix will be available in a new version?

We are waiting for the tests to validate the change, I have no date for this change yet.
@saqwel has this change impacted your use of pREST?

**Comment by saqwel** [comment]
@avelino yes. We use third-party Postgres infrastructure where every database contains hyphens in their name. Main scenario of usage pREST is inserting data to database. So pREST almost completely useless for us, meanwhile pREST looks like the best REST implementation for Postgres.

**Comment by avelino** [comment]
> @avelino yes. We use third-party Postgres infrastructure where every database contains hyphens in their name. Main scenario of usage pREST is inserting data to database. So pREST almost completely useless for us, meanwhile pREST looks like the best REST implementation for Postgres.

can you contribute to the implementation of these tests?

**Comment by saqwel** [comment]
> can you contribute to the implementation of these tests?

I can try if it does not required development with Go. I have never participated in tests impementation on Github.

**Comment by avelino** [comment]
Solved this problem, gave more work to write the tests, so I created a new branch and spent the day working on it.

I'm sorry @sarath16933 for not being able to keep the credits (commts)

**Comment by saqwel** [comment]
It works great now. Thank you very much.

**Pull request closed without merging**
