### PR TITLE
goreleaser: Current docker image broken

### PR DESCRIPTION
**Pull request by avelino**
ref: #391

### CODE REVIEW

**Comment by avelino** [comment]
help pls pls pls @caarlos0

**Comment by felipeweb** [comment]
gorealeaser does not support CGO yet https://goreleaser.com/limitations/cgo/

**Comment by caarlos0** [comment]
do you need CGO? if not, you can disable it...

**Comment by felipeweb** [comment]
@avelino maybe we missing some flags on build. Could you try add the flag equal here https://github.com/gosidekick/migration/blob/master/.goreleaser.yml ?

**Comment by avelino** [comment]
> @avelino maybe we missing some flags on build to work at alpine image. Could you try add the flag equal here https://github.com/gosidekick/migration/blob/master/.goreleaser.yml ?

very good, I will test

removes the docker image generation from the goreleaser and put it on travis (github release is on the goreleaser)

I'm going to open an issue to work with the migration of the docker image to gorelease - so I can work with more time.

**Comment by avelino** [comment]
> do you need CGO? if not, you can disable it...

@caarlos0 cgo off was giving trouble generating docker image

**Pull request merged**
