### PR TITLE
avoid panic on tx.commit calls

### PR DESCRIPTION
**Pull request by avelino**
ref: https://github.com/prest/adapters/pull/55 by @arxdsilva 

While using this mock pkg I came across a commit panic when the mock tx was used to commit. I made a branch that shows how this panic occurs ([here](https://github.com/levpay/adapters/blob/6c57b4806c971fe7ff17f7e631aaca39d1fcf0a8/mock/mock_test.go#L436)).

This PR does:
- makes `Mock` struct implement the driver.Driver interface
- registers a new driver "mock" on `New`
- returns a fake db tx on `mock.GetTransaction`
- implements `mockConn` that allows `Mock{}` to return a mocked connection

> We are in the process of centralizing the repository to simplify the contribution and maintainability of pREST.
> I have taken care to maintain the credit of the contribution (commit history)

### CODE REVIEW

**Comment by avelino** [comment]
@arxdsilva can you understand the mistake that happened? help-me pls

**Comment by arxdsilva** [comment]
:(
image

basically is set the packages on `go.mod`

```go
module github.com/prest/prest/adapters

go 1.13

require (
	github.com/jmoiron/sqlx v1.2.0
	github.com/lib/pq v1.8.0
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	github.com/nuveo/log v0.0.0-20190430190217-44d02db6bdf8
	github.com/prest/prest/config v0.0.0-20200729162849-86fce87522f2
	github.com/prest/prest/template v0.0.0-20200729180256-565f3bc1ae70
	github.com/spf13/viper v1.7.0 // indirect
	github.com/stretchr/testify v1.3.0
)

```

**Comment by tiaguinho** [comment]
@arxdsilva you are 4 commits behind the master branch.
Try to do a ```git rebase master```. This will probably fix the problem with CI.

**Comment by avelino** [comment]
@tiaguinho can you resolve this PR conflict and solve the bug so we can merge?

**Comment by tiaguinho** [comment]
@avelino on it.

**Comment by tiaguinho** [comment]
I had to remove the assert package because isn't working in go 1.10, 1.11, and 1.12.

**Comment by avelino** [comment]
Thanks @arxdsilva (cc @levpay)

**Pull request merged**
