### PR TITLE
Change JSON_AGG to JSONB_AGG, enabling better performance on the DBMS

### PR DESCRIPTION
**Pull request by vmesel**
This change enables us to perform better on our aggregation and API response time, without changing the whole serializing code. 

If this PR gets merged, we can work on the future on a new serializer.

fixed: #730

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
`jsonb_agg` was **implemented in postgers version 9.5** (no earlier versions), we need to update in the documentation and in the README that prestd supports postgres version 9.5+

https://www.postgresql.org/docs/9.5/functions-aggregate.html

**Review by avelino — CHANGES_REQUESTED** [review]
some things changed in the return, this made some tests break
```
test: TestShowTable body: [{"position": 1, "data_type": "integer", "max_length": 32, "table_name": "test", "column_name": "id", "is_nullable": "NO", "is_generated": "NEVER", "is_updatable": "YES", "table_schema": "public", "default_value": "nextval('test_id_seq'::regclass)"}, {"position": 2, "data_type": "text", "max_length": null, "table_name": "test", "column_name": "name", "is_nullable": "YES", "is_generated": "NEVER", "is_updatable": "YES", "table_schema": "public", "default_value": null}]
test: TestShowTable body: [{"position": 1, "data_type": "text", "max_length": null, "table_name": "test2", "column_name": "name", "is_nullable": "YES", "is_generated": "NEVER", "is_updatable": "YES", "table_schema": "public", "default_value": null}, {"position": 2, "data_type": "integer", "max_length": 32, "table_name": "test2", "column_name": "number", "is_nullable": "YES", "is_generated": "NEVER", "is_updatable": "YES", "table_schema": "public", "default_value": null}]
test: TestShowTable body: database not registered: invalid
```

**Comment by vmesel** [comment]
@avelino how do I setup the test env on my machine?

**Comment by vmesel** [comment]
These test errors look like something in the environment. It appears to be that the code is not able to reach the database.

**Comment by arxdsilva** [comment]
> `jsonb_agg` was **implemented in postgers version 9.5** (no earlier versions), we need to update in the documentation and in the README that prestd supports postgres version 9.5+
> 
> https://www.postgresql.org/docs/9.5/functions-aggregate.html

maybe related to https://github.com/prest/prest/issues/623

**Comment by vmesel** [comment]
@avelino @arxdsilva tests fixed.

**Review by avelino — APPROVED** [review]
LGTM

**Comment by avelino** [comment]
@arxdsilva after this PR is accepted we have to generate a nice content (text) release talking about the performance improvement

Writing a text in [dev.to/prestd](https://dev.to/prestd) would be nice too

**Review by fabriziomello — APPROVED** [review]
LGTM

**Comment by vmesel** [comment]
@avelino I can do it!

**Review by arxdsilva — APPROVED** [review]

**Comment by arxdsilva** [comment]
thank you @vmesel for the analysis and hard work!

**Pull request merged**
