### PR TITLE
AWS Lambda support

### PR DESCRIPTION
**Pull request by aodhan-domhnaill**
Add's basic support for executing prest/prest in an AWS Lambda function

ref: #381

### CODE REVIEW

**Comment by aidan-plenert-macdonald** [comment]
Sorry for the delay.

Next step would be to create tests that call the lambda handler. Similar to how you would write HTTP unit tests.

Then I think a couple templates could be created so this could be deployed like your Heroku one click setup.

Do you have unit tests for the HTTP calls?

**Comment by avelino** [comment]
Understanding your proposal is important to write in adapter format, so we can support other serverless (GCP, OpenFaas, ...)

**Comment by aidan-plenert-macdonald** [comment]
Hey, sorry it took a while. The code is now working and I added some simple tests in the docs. Let me know if you have a good way to automate the test.

**Comment by avelino** [comment]
Too bad you don't want to help us with functions (AWS lambda)

**Pull request closed without merging**
